#include "nsISupports.idl"

interface mhIHeader;

[scriptable, uuid(feb80fc3-9e72-4fc5-bc72-986957ada6cc)]
interface nsIModifyheaders : nsISupports
{
    attribute unsigned long count;
    attribute boolean active;
    attribute boolean openAsTab;
    attribute boolean windowOpen;

    string getHeaders();
    void saveHeaders(in string headersJSON);
};